import express from 'express';
import cors from 'cors';
import JSZip from 'jszip';
import fetch from 'node-fetch';
const app=express();
const allowed=(process.env.FRONTEND_ORIGIN||'https://vineetgupta65488-cell.github.io').split(',').map(x=>x.trim());
app.use(cors({origin:(origin,cb)=>{if(!origin||allowed.includes(origin)||allowed.includes('*'))return cb(null,true);cb(new Error('CORS origin not allowed'))}}));
app.use(express.json());
const PORT=process.env.PORT||3000;
const feeds=[{id:'delhi',state:'Delhi',name:'Delhi public GTFS',url:process.env.DELHI_GTFS_URL},{id:'maharashtra',state:'Maharashtra',name:'Maharashtra public GTFS',url:process.env.MAHARASHTRA_GTFS_URL},{id:'karnataka',state:'Karnataka',name:'Karnataka public GTFS',url:process.env.KARNATAKA_GTFS_URL},{id:'tamil-nadu',state:'Tamil Nadu',name:'Tamil Nadu public GTFS',url:process.env.TAMIL_NADU_GTFS_URL},{id:'telangana',state:'Telangana',name:'Telangana public GTFS',url:process.env.TELANGANA_GTFS_URL},{id:'uttar-pradesh',state:'Uttar Pradesh',name:'Uttar Pradesh public GTFS',url:process.env.UP_GTFS_URL},{id:'haryana',state:'Haryana',name:'Haryana public GTFS',url:process.env.HARYANA_GTFS_URL}].filter(x=>x.url);
const db=new Map();
function csv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(v=>v!==''))rows.push(row);row=[];cell='';continue}cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}const h=rows.shift()||[];return rows.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??''])))}
async function ingest(feed){const res=await fetch(feed.url);if(!res.ok)throw new Error(`Feed HTTP ${res.status}`);const zip=await JSZip.loadAsync(await res.arrayBuffer());const out={routes:[],stops:[],trips:[],stop_times:[]};for(const f of Object.keys(zip.files)){const k=f.replace('.txt','');if(k in out)out[k]=csv(await zip.files[f].async('text'))}const agencies=Object.fromEntries(out.routes.map(r=>[r.route_id,r]));db.set(feed.id,{...feed,...out,updated:new Date().toISOString(),routeMap:agencies,stopMap:Object.fromEntries(out.stops.map(s=>[s.stop_id,s]))});return db.get(feed.id)}
function findStop(feed,q){const s=q.toLowerCase().trim();return feed.stops.filter(x=>(x.stop_name||'').toLowerCase().includes(s)).slice(0,30)}
function routeLabel(r){return r.route_short_name||r.route_long_name||null}
function segment(feed,r,sts,a,b){return {route_id:r.route_id,route_number:routeLabel(r),route_name:r.route_long_name||r.route_short_name||null,agency_id:r.agency_id||null,from:feed.stopMap[sts[a].stop_id]?.stop_name||sts[a].stop_id,to:feed.stopMap[sts[b].stop_id]?.stop_name||sts[b].stop_id,stops:sts.slice(a,b+1).map(x=>({id:x.stop_id,name:feed.stopMap[x.stop_id]?.stop_name||x.stop_id,arrival:x.arrival_time||null,departure:x.departure_time||null}))}}
function journeys(feed,from,to){const fs=findStop(feed,from),ts=findStop(feed,to);if(!fs.length||!ts.length)return[];const F=new Set(fs.map(x=>x.stop_id)),T=new Set(ts.map(x=>x.stop_id)),byTrip={};for(const st of feed.stop_times)(byTrip[st.trip_id]??=[]).push(st);const direct=[];for(const [tripId,raw] of Object.entries(byTrip)){const sts=raw.slice().sort((a,b)=>Number(a.stop_sequence)-Number(b.stop_sequence));let a=-1,b=-1;for(let i=0;i<sts.length;i++){if(a<0&&F.has(sts[i].stop_id))a=i;if(a>=0&&T.has(sts[i].stop_id)){b=i;break}}if(a>=0&&b>a){const tr=feed.trips.find(x=>x.trip_id===tripId),r=tr&&feed.routes.find(x=>x.route_id===tr.route_id);if(r)direct.push({type:'direct',trip_id:tripId,legs:[segment(feed,r,sts,a,b)]})}}return direct.slice(0,10)}
app.get('/health',(req,res)=>res.json({ok:true,feeds:feeds.map(f=>({id:f.id,state:f.state,loaded:db.has(f.id),source:f.name}))}));
app.post('/admin/feeds/:id/refresh',async(req,res)=>{const f=feeds.find(x=>x.id===req.params.id);if(!f)return res.status(404).json({error:'Unknown feed'});try{const d=await ingest(f);res.json({ok:true,id:f.id,updated:d.updated,routes:d.routes.length,stops:d.stops.length,trips:d.trips.length,stop_times:d.stop_times.length})}catch(e){res.status(502).json({error:e.message})}});
app.get('/api/v1/stops/search',async(req,res)=>{const {state,q}=req.query;if(!state||!q)return res.status(400).json({error:'state and q are required'});const f=feeds.find(x=>x.state.toLowerCase()===state.toLowerCase());if(!f)return res.json({status:'no_feed',stops:[]});if(!db.has(f.id))try{await ingest(f)}catch(e){return res.status(502).json({status:'feed_error',message:e.message,stops:[]})}res.json({status:'ok',stops:findStop(db.get(f.id),q).map(s=>({id:s.stop_id,name:s.stop_name,lat:s.stop_lat,lon:s.stop_lon}))})});
app.get('/api/v1/journeys',async(req,res)=>{const {state,from,to}=req.query;if(!state||!from||!to)return res.status(400).json({error:'state, from and to are required'});const f=feeds.find(x=>x.state.toLowerCase()===state.toLowerCase());if(!f)return res.json({status:'no_feed',message:`No verified transport feed is configured for ${state}.`,journeys:[]});if(!db.has(f.id))try{await ingest(f)}catch(e){return res.status(502).json({status:'feed_error',message:e.message,journeys:[]})}const js=journeys(db.get(f.id),from,to);res.json({status:js.length?'ok':'no_verified_journey',source:f.name,journeys:js})});
app.listen(PORT,()=>console.log(`RoutePulse API listening on ${PORT}`));